name: Publish Python-only Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # This is needed so that all tags are loaded (important for setuptools_scm)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade build twine
    - name: Build package using `build`
      env:
        CHOLUPDATES_DISABLE_CYTHON_BUILD: 1
      run: |
        python -m build
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*-py3-none-any.whl
